### ISSUE TITLE
Error in env variable comparison and parameter parsing in createVoiceResponse

### ISSUE THREAD

**Issue by devjeff** [TwilioDevEd/voice-javascript-sdk-quickstart-java#15]
I've noticed 2 errors in the code:

1. The comparison with the environment variable TWILIO_CALLER_ID must be performed via the equals method and not the == parameter. The == comparison always yields false.

2. The parsing of the argument "to" (recipient) is not correct. The code checks for the request parameter "To" first and then tries to retrieve the value from the parameter "phone". The "phone" parameter is only checked if the variable "to" is null, which is not enough, as might also be an empty string.

**Comment by devjeff** [comment]
I've created a pull request:
[16](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-java/pull/16)

**Comment by bld010** [comment]
Merged. Thank you!
